name: houseasy_teste_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  lottie: ^2.3.2
  flutter_animate: ^4.1.1+1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  go_router: ^6.5.9
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  firebase_auth_mocks: ^0.10.3
  mock_exceptions: ^0.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700
