// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7WF6nTCCMZllHUtQBcoHS81uFSEvof8',
    appId: '1:122347414924:web:2ab670b7bce7a15eff62a9',
    messagingSenderId: '122347414924',
    projectId: 'houseasytest-c4b1c',
    authDomain: 'houseasytest-c4b1c.firebaseapp.com',
    storageBucket: 'houseasytest-c4b1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXouSyGLJ3J6Uo9eOsbcQ0-mfoZ11pek',
    appId: '1:122347414924:android:008948313340b911ff62a9',
    messagingSenderId: '122347414924',
    projectId: 'houseasytest-c4b1c',
    storageBucket: 'houseasytest-c4b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_4zg3rjHOH9gbMS7pXoV0-EhJqxcotE',
    appId: '1:122347414924:ios:67ad0b64b1cc6c74ff62a9',
    messagingSenderId: '122347414924',
    projectId: 'houseasytest-c4b1c',
    storageBucket: 'houseasytest-c4b1c.appspot.com',
    iosClientId: '122347414924-qu08beevorvtol7aopg4a0et1oovola7.apps.googleusercontent.com',
    iosBundleId: 'net.houseasy.houseasyTesteFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_4zg3rjHOH9gbMS7pXoV0-EhJqxcotE',
    appId: '1:122347414924:ios:67ad0b64b1cc6c74ff62a9',
    messagingSenderId: '122347414924',
    projectId: 'houseasytest-c4b1c',
    storageBucket: 'houseasytest-c4b1c.appspot.com',
    iosClientId: '122347414924-qu08beevorvtol7aopg4a0et1oovola7.apps.googleusercontent.com',
    iosBundleId: 'net.houseasy.houseasyTesteFrontend',
  );
}
